diary/urls.py
from django.urls import path
from django.contrib import admin
# 이미지를 업로드하자
from django.conf.urls.static import static
from django.conf import settings

from .views import base_views, diary_views, answer_views

app_name = 'diary'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('diary/', base_views.diary_list, name='diary_list'),
    path('diary_ajax/', base_views.diary_ajax, name='diary_ajax'),
    path('diary/every', base_views.diary_every, name='diary_every'),
    path('diary/<int:diary_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:diary_id>/', answer_views.answer_create, name='answer_create'),
    path('diary/create/', diary_views.diary_create, name='diary_create'),
    path('diary/modify/<int:diary_id>/', diary_views.diary_modify, name='diary_modify'),
    # path('diary/delete_photo/<int:diary_id>/', diary_views.delete_photo, name='delete_photo'),
    path('diary/delete/<int:diary_id>/', diary_views.diary_delete, name='diary_delete'),
    path('answer/modify/<int:answer_id>/<int:diary_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/<int:diary_id>/', answer_views.answer_delete, name='answer_delete'),
    path('diary/vote/<int:diary_id>/', base_views.diary_vote, name='diary_vote'),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db import models
from django.db.models.fields.related import ManyToManyField

from datetime import datetime

class CreateDiary(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_diary')
    diary_id = models.AutoField(primary_key=True)
    date = models.CharField(max_length=30,blank=True,null=True)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(blank=True, null=True)
    weather = models.CharField(max_length=30)
    mood = models.CharField(max_length=30)
    title = models.CharField(max_length=200)
    content = models.TextField()
    photo = models.ImageField(blank=True,null=True, upload_to='diary_photo/')
    reflection = models.CharField(max_length=200, blank=True, null=True)
    voter = models.ManyToManyField(User, related_name='voter_diary')
    praise = models.CharField(max_length=200, blank=True, null=True)
    disclose_choice= (
        ('public', '공개'),
        ('private', '비공개'),
    )
    disclose = models.CharField(max_length=20, choices=disclose_choice, default='public')

    def __str__(self):
        return self.title

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    question = models.ForeignKey(CreateDiary, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(blank=True, null=True)

diary/forms.py
from django import forms
from diary.models import CreateDiary, Answer


class DiaryForm(forms.ModelForm):
    class Meta:
        model = CreateDiary  # 사용할 모델
        fields = ['weather', 'mood', 'title', 'content', 'photo', 'reflection', 'praise', 'disclose', 'create_date', 'modify_date']  # QuestionForm에서 사용할 Question 모델의 속성
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']  # create_date 필드 제외
        labels = {
            'content': '답변내용',
        }

diary/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import CreateDiary
from django.utils import timezone

def index(request):
    diary_list = CreateDiary.objects.order_by('-create_date')
    context = {'diary_list':diary_list}
    return render(request, 'diary/diary_list.html', context)

def detail(request, diary_id):
    diary = CreateDiary.objects.get(diary_id=diary_id)
    context = {'diary':diary}
    return render(request, 'diary/diary_detail.html', context)

def answer_create(request, diary_id):
    question = get_object_or_404(CreateDiary, pk=diary_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('diary:detail', diary_id=diary_id)

diary/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect
from ..models import CreateDiary, Answer
from django.utils import timezone
from ..models import CreateDiary
from ..forms import DiaryForm, AnswerForm
from django.core.paginator import Paginator  
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Count


@login_required(login_url='common:login')
def answer_create(request, diary_id):
    diary = get_object_or_404(CreateDiary, pk=diary_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = diary
            answer.save()
            return redirect('diary:detail', diary_id=diary.diary_id)
    else:
        form = AnswerForm()
    context = {'diary': diary, 'form': form}
    return render(request, 'diary/diary_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id, diary_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    diary = get_object_or_404(CreateDiary, pk=diary_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('diary:detail', diary_id=diary.diary_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('diary:detail', diary_id=diary.diary_id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'diary/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id, diary_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    diary = get_object_or_404(CreateDiary, pk=diary_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('diary:detail', diary_id=diary.diary_id)

diary/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from ..models import CreateDiary, Answer
from django.utils import timezone
from ..forms import DiaryForm, AnswerForm
from django.core.paginator import Paginator  
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Count
from django.db.models import Q 
from django import template
from ..templatetags.custom_date import relative_time
from common.views import mypage
from common.media_form import UserProfile
from datetime import date
from django.http import JsonResponse
from django.forms.models import model_to_dict
from datetime import timedelta

register = template.Library()
register.filter('relative_time', relative_time)

def index(request):
    return render(request, 'index.html')

def diary_list(request):
    year = request.GET.get('year')
    month = request.GET.get('month')
    day = request.GET.get('day')
    
    if year and month and day:
        try:
            day = int(day)
            # day 값에서 1을 빼기
            day += 1
            create_date = date(int(year), int(month), day)
        except ValueError:
            create_date = None
    else :
        create_date = None

    if create_date:
        diary_list = CreateDiary.objects.filter(
            author_id=request.user.id,
            create_date=create_date
        ).order_by('-create_date')
    else:
        diary_list = CreateDiary.objects.filter(author_id=request.user.id).order_by('-create_date')

    paginator = Paginator(diary_list, 10) # 페이지당 10개씩 보여주기
    page = request.GET.get('page','1') # 페이지
    page_obj = paginator.get_page(page)

    context = {'diary_list':page_obj}

    return render(request, 'diary/diary_list.html', context)

def diary_ajax(request):
    year = request.GET.get('year')
    month = request.GET.get('month')
    day = request.GET.get('day')
    
    if year and month and day:
        try:
            create_date = date(int(year), int(month), int(day) )
        except ValueError:
            create_date = None
    else :
        create_date = None

    if create_date:
        diary_list = CreateDiary.objects.filter(
            author_id=request.user.id,
            create_date=create_date
        ).order_by('-create_date')
    else:
        diary_list = CreateDiary.objects.filter(author_id=request.user.id).order_by('-create_date')

    data = []
    for diary in diary_list:
        print('diary : ', diary)
        diary_dict = model_to_dict(diary)
        # 필요한 필드만 선택하여 딕셔너리에 추가
        diary_data = {
            'create_date': diary_dict['create_date'],
            'title': diary_dict['title'],
            'disclose': diary_dict['disclose'],
            # 필요한 필드 추가
        }
        data.append(diary_data)
    return JsonResponse(data, safe=False)


def detail(request, diary_id):
    diary = CreateDiary.objects.get(diary_id=diary_id)
    create_date = diary.create_date
    previous_day = create_date - timedelta(days=1)

    try:
        user_profile = UserProfile.objects.get(user_id=diary.author_id)
        if user_profile :
            image_path = user_profile.profile_image.url if user_profile.profile_image else None
        else:
            image_path = None
    except UserProfile.DoesNotExist:
        image_path = None

    context = {'diary':diary, 'image_path':image_path, 'previous_day': previous_day}
    return render(request, 'diary/diary_detail.html', context)


@login_required(login_url='common:login')
def diary_vote(request, diary_id):
    diary = get_object_or_404(CreateDiary, pk=diary_id)
    if request.user == diary.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        diary.voter.add(request.user)
    return redirect('diary:detail', diary_id=diary.diary_id)

def diary_every(request):
    page = request.GET.get('page','1') # 페이지
    diary_list2 = CreateDiary.objects.filter(disclose='public').order_by('-create_date')
    
    # Best Diaries comment
    most_common_questions = Answer.objects.values('question_id').annotate(question_count=Count('question_id')).order_by('-question_count')[:3]
    best_diaries = [CreateDiary.objects.get(pk=question['question_id']) for question in most_common_questions]
    
    # Best Diaries recommend
    recommend_questions = CreateDiary.objects.annotate(voter_count=Count('voter')).order_by('-voter_count')[:3]

    # 검색 
    
    content = request.GET.get('content','전체')
    kw = request.GET.get('kw', '')  # 검색어

    if content == '전체':
        diary_list2 = diary_list2
    elif content == '제목/내용':
        diary_list2 = diary_list2.filter(
            Q(title__icontains=kw)  # 제목 검색
        ).distinct()
    elif content == '답변':
        diary_list2 = diary_list2.filter(
            Q(content__icontains=kw)  # 내용 검색
        ).distinct()
    elif content == '일기 글쓴이':
        diary_list2 = diary_list2.filter(
            Q(author__username__icontains=kw)  # 질문 글쓴이 검색
        ).distinct()
    elif content == '답변 글쓴이':
        diary_list2 = diary_list2.filter(
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    else :
        diary_list2 = diary_list2.filter(
            Q(title__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    # kw = request.GET.get('kw', '')  # 검색어
    # if kw:
    #     diary_list2 = diary_list2.filter(
    #         Q(title__icontains=kw) |  # 제목 검색
    #         Q(content__icontains=kw) |  # 내용 검색
    #         Q(answer__content__icontains=kw) |  # 답변 내용 검색
    #         Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
    #         Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
    #     ).distinct()


    paginator = Paginator(diary_list2, 10) # 페이지당 10개씩 보여주기                                                   
    page_obj = paginator.get_page(page)

    context = {
        'diary_list2':page_obj,
        'best_diaries': best_diaries,
        'recommend_questions': recommend_questions,
        'page': page, 'kw': kw
    }

    return render(request, 'diary/diary_every_list.html', context)

diary/views/diary_views.py
from django.shortcuts import render, get_object_or_404, redirect
from ..models import CreateDiary
from django.utils import timezone
from ..models import CreateDiary
from ..forms import DiaryForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url='common:login')
def diary_create(request):
    if request.method == 'POST':
        form = DiaryForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = form.cleaned_data['create_date']
            question.photo = request.FILES.get('photo')
            question.save()
            return redirect('diary:index')
    else:
        form = DiaryForm()

    
    context = {'form': form}
    return render(request, 'diary/diary_form.html', context)


@login_required(login_url='common:login')
def diary_modify(request, diary_id):
    diary = get_object_or_404(CreateDiary, pk=diary_id)
    if request.user != diary.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('diary:detail', diary_id=diary.diary_id)
    if request.method == "POST":
        form = DiaryForm(request.POST, request.FILES, instance=diary)
        if form.is_valid():
            diary = form.save(commit=False)
            diary.modify_date = timezone.now()  # 수정일시 저장
            if 'img_delete' in request.POST:
                diary.photo.delete()  # 이미지 삭제
            diary.save()
            return redirect('diary:detail', diary_id=diary.diary_id)
    else:
        form = DiaryForm(instance=diary)
    context = {'form': form}
    return render(request, 'diary/diary_modify.html', context)


@login_required(login_url='common:login')
def diary_delete(request, diary_id):
    diary = get_object_or_404(CreateDiary, pk=diary_id)
    if request.user != diary.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('diary:detail', diary_id=diary.diary_id)
    diary.delete()
    return redirect('diary:index')

templates/diary/answer_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/diary/diary_form.css' %}">
<script src="{% static 'js/diary/diary_form.js' %}"></script>


<main>
    <div class="container">
        <!-- 답변 수정-->
        <form method="post">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="content" class="form-label">답변내용</label>
                <textarea class="form-control" name="content" id="content"
                        rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
</main>
{% endblock %}

templates/diary/diary_detail.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/diary/diary_detail.css' %}">
    <main>
        <div class="container">
            <div class="diary_detail_box">
                <h1>{{ diary.title }}</h1>
                <div class="content_box">
                    <input type="hidden" name="disclose" value="{{ diary.disclose }}">
                    <div class="diary_id" id="{{ diary.diary_id }}"></div>
                    <div class="error_box">
                        {% if messages %}
                            <div class="alert alert-danger" role="alert">
                        {% for message in messages %}
                                <div class="alert_inner">
                                    <strong>{{ message.tags }}</strong>
                                    <span>{{ message.message }}</span>
                                </div>
                        {% endfor %}
                            </div>
                        {% endif %}
                        <!-- 넌필드 오류 -->
                        {% for error in form.non_field_errors %}
                        <div style="background: #e3f7fc;
                                    padding: 10px 20px;
                                    box-sizing: border-box;
                                    border-radius: 10px;
                                    border: 2px solid #b9e7f9;
                                    text-align: center;
                                    color: #555555;
                                    font-size: 15px;">
                            <strong style="color: #03a9f4;">{{ error }}</strong>
                        </div>
                        {% endfor %}
                    </div>
                    
                    <div class="date_user_box">
                        <div class="user_box">
                            <div class="user_photo">
                                {% if image_path   %}
                                <!-- <img src="{{image_path }}" alt="Profile Image" style="max-width: 200px; max-height: 200px;"><br><br> -->
                                <div class="user_photo_background" style="background: url({{image_path }}); background-position: center; background-size: cover; background-repeat: no-repeat;"></div>
                                {% else %}
                                <div class="user_photo_background" style="background: url({% static 'img/common/default_image.png' %}); background-position: center; background-size: cover; background-repeat: no-repeat;"></div>
                                {% endif %}
                            </div>
                            <div class="user_name">{{ diary.author.username }}</div>
                        </div>
                        <div class="date_box previous_day" id="{{ previous_day|date:'Y.m.d' }}">{{ previous_day|date:"Y.m.d" }}</div> <br><br>
                        {% if diary.modify_date %}
                            <div class="date_box modify_date">{{ diary.modify_date|date:"Y.m.d" }}</div>
                        {% endif %}
                    </div>

                    <div class="ext_box">
                        <div class="text_box">
                            <span>날씨</span>
                            <span>{{ diary.weather }}</span> 
                        </div>
                        <div class="text_box">
                            <span>기분</span>
                            <span>{{ diary.mood }}</span>
                            
                        </div>
                    </div>

                    <div class="main_content_box">
                        <div class="main_photo">
                            {% if diary.photo %}
                                <div class="img" style="background: url({{ diary.photo.url }}); background-position: center; background-size: cover; background-repeat: no-repeat;"></div>
                            {% else %}
                                <div></div>
                            {% endif %}
                        </div>
                        <div class="main_text">{{ diary.content|linebreaksbr }}</div>
                    </div>
                    
                    <div class="today_ext_box">
                        <div>
                            <span>오늘의 반성</span>
                            {% if diary.reflection %}
                                <span>{{ diary.reflection|linebreaksbr }}</span>
                            {% else %}
                                <span style="color: #ddd; text-align: center;">Nothing</span>
                            {% endif %}
                        </div>
                        <div>
                            <span>오늘의 칭찬</span>
                            {% if diary.praise %}
                                <span>{{ diary.praise|linebreaksbr }}</span>
                            {% else %}
                                <span style="color: #ddd; text-align: center;">Nothing</span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="btns_box">
                        <a href="javascript:void(0)" data-uri="{% url 'diary:diary_vote' diary.diary_id  %}"
                            class="recommend"> 추천
                            <span>{{diary.voter.count}}</span>
                        </a>
                        <div class="update_btn_box">
                            {% if request.user == diary.author %}
                                <a href="javascript:void(0)" class="update_btn">수정</a>
                            {% endif %}
                            <a href="javascript:void(0)" class="delete delete_btn"
                            data-uri="{% url 'diary:diary_delete' diary.diary_id  %}">삭제</a>
                        </div>
                    </div>
                </div>

                <div class="answer_box">                    
                    {% if diary.disclose == 'public' %}
                        <h5 class="answer_count">{{ diary.answer_set.count }}개의 답변이 있습니다</h5>
                    {% endif %}

                    
                    {% if diary.disclose == 'public' %}
                    <div class="answer_write_btn">답변 입력하기</div>
                    <form action="{% url 'diary:answer_create' diary.diary_id %}" method="post">
                        {% csrf_token %}
                        <textarea name="content" id="content" rows="15"></textarea>
                        <input type="submit" value="등록" class="answer_submit">
                    </form>
                    {% endif %}


                    <div class="answer_text_box">
                        <ul class="answer_ul">
                            {% for answer in diary.answer_set.all %}
                                <li>
                                    <div class="answer_ext_box">
                                        <span>
                                            {% if answer.author %}
                                                {{ answer.author.username }} 
                                            {% endif %}
                                        </span>
                                        <span>
                                            {% if answer.modify_date %}
                                            <div class="badge bg-light text-dark p-2 text-start mx-3">
                                                <div>{{ answer.modify_date|date:"Y.m.d" }}</div>
                                            </div>
                                            {% else %}
                                                {{ answer.create_date|date:"Y.m.d" }}                                                
                                            {% endif %}
                                        </span>
                                    </div>
                                    
                                    <span>{{ answer.content }}</span>
                                    
                                    
                                    <div class="answer_btn_box">
                                        {% if request.user == answer.author %}
                                            <a href="{% url 'diary:answer_modify' answer.id diary.diary_id %}" 
                                                class="answer_update_btn">수정</a>
                                            <a href="#" class="answer_delete_btn"
                                                data-uri="{% url 'diary:answer_delete' answer.id diary.diary_id  %}">삭제</a>
                                        {% endif %}
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>

            </div>
        </div>
    </main>

{% endblock %}

{% block script %}
    <script type='text/javascript'>
        const delete_elements = document.getElementsByClassName("delete");
        Array.from(delete_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                if(confirm("정말로 삭제하시겠습니까?")) {
                    location.href = this.dataset.uri;
                };
            });
        });

        const recommend_elements = document.getElementsByClassName("recommend");
        Array.from(recommend_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                if(confirm("정말로 추천하시겠습니까?")) {
                    location.href = this.dataset.uri;
                };
            });
        });

        $(document).ready(function(){
            var year = $('.previous_day').attr('id').split('.')[0];
            var month = $('.previous_day').attr('id').split('.')[1];
            var day = $('.previous_day').attr('id').split('.')[2];
            var ids2 = $('.diary_id').attr('id');
            console.log('id2 : ', ids2)
            var diaryListURL = '/diary/modify/'+ids2+'?year=' + year + '&month=' + month + '&day=' + (Number(day)+1);
            $('.update_btn').on('click',function(){
                // GET 요청 보내기
                $.ajax({
                    type: "GET",
                    url: diaryListURL,
                    success: function(response) {
                        window.location.href = diaryListURL;
                    },
                    error: function(xhr, errmsg, err) {
                        console.log('GET 요청이 실패했습니다.');
                        console.log(xhr, errmsg, err);
                    }
                });
            });

            $('.answer_write_btn').on('click',function(){
                $('.answer_box form').css('display','inline-block')
                $(this).css('display','none')
            })
            if ($('.modify_date').length > 0) {
                $('.previous_day').css('display', 'none')
            } 
        })
    </script>
{% endblock %}

templates/diary/diary_list.html
{% extends 'base.html' %}

{% load custom_date %}
{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/diary/diary_list.css' %}">
<main>
    <div class="container">
        
        {% if diary_list %}
            <ul class="list_ul">
            {% for diary in diary_list %}
                <li>
                    <a href="{% url 'diary:detail' diary.diary_id %}">
                        <span style="display: flex; gap: 30px;">
                            <span>{{ diary_list.paginator.count|sub:diary_list.start_index|sub:forloop.counter0|add:1 }}</span>
                            <span>{{ diary.title }}</span>
                            {% if diary.answer_set.count > 0 %}
                            <span class="text-danger small mx-2" style="font-size: 11px; color: red;">{{ diary.answer_set.count }}</span>
                            {% endif %}
                            <span>{{ diary.author.username }}</span>
                        </span>
                        <span>{{ diary.create_date|relative_time }}</span>
                    </a>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>일기를 작성해주세요~ :D</p>
        {% endif %}

        {% if diary_list %}
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="?page=1"><<</a>
                </li>
                <!-- 이전페이지 -->
                {% if diary_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ diary_list.previous_page_number }}"><</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><</a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in diary_list.paginator.page_range %}
                {% if page_number == diary_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if diary_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ diary_list.next_page_number }}">></a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">></a>
                </li>
                {% endif %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">>></a>
                </li>
            </ul>
            <!-- 페이징처리 끝 -->
        
        {% endif %} 
        <a href="{% url 'diary:diary_create' %}" class="create_diary_btn">일기 적기</a>
    </div>
</main>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        const urlParams = new URL(location.href).searchParams;
        const year = urlParams.get('year');
        const month = urlParams.get('month');
        const day = urlParams.get('day');

        var diaryListURL = '/diary/create/?year=' + year + '&month=' + month + '&day=' + (Number(day)+1);
        $('.create_diary_btn').on('click',function(){
           

            // GET 요청 보내기
            $.ajax({
                type: "GET",
                url: diaryListURL,
                success: function(response) {
                    window.location.href = diaryListURL;

                },
                error: function(xhr, errmsg, err) {
                    console.log('GET 요청이 실패했습니다.');
                    console.log(xhr, errmsg, err);
                }
            });
        });
    })
</script>
{% endblock %}