common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import reset_views,user_views

app_name = 'common'

urlpatterns = [
    path('my_page/', user_views.mypage, name='mypage'),
    path('profile/', user_views.profile, name='profile'),
    path('profile_update/', user_views.profile_update, name='profile_update'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('signup/', user_views.signup, name='signup'),
    path('update/', user_views.update, name='update'),
    path('modify_password/', user_views.modify_password, name='modify_password'),
    path('delete/', user_views.delete, name='delete'),

    path('password_reset', reset_views.UserPasswordResetView.as_view()),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(template_name='common/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', reset_views.UserPasswordResetConfirmView.as_view(template_name='common/set_password.html'), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='common/set_password_done.html'), name="password_reset_complete"),
]

diary/urls.py
from django.urls import path
from django.contrib import admin
# 이미지를 업로드하자
from django.conf.urls.static import static
from django.conf import settings

from .views import base_views, diary_views, answer_views

app_name = 'diary'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('diary/', base_views.diary_list, name='diary_list'),
    path('diary_ajax/', base_views.diary_ajax, name='diary_ajax'),
    path('diary/every', base_views.diary_every, name='diary_every'),
    path('diary/<int:diary_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:diary_id>/', answer_views.answer_create, name='answer_create'),
    path('diary/create/', diary_views.diary_create, name='diary_create'),
    path('diary/modify/<int:diary_id>/', diary_views.diary_modify, name='diary_modify'),
    # path('diary/delete_photo/<int:diary_id>/', diary_views.delete_photo, name='delete_photo'),
    path('diary/delete/<int:diary_id>/', diary_views.diary_delete, name='diary_delete'),
    path('answer/modify/<int:answer_id>/<int:diary_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/<int:diary_id>/', answer_views.answer_delete, name='answer_delete'),
    path('diary/vote/<int:diary_id>/', base_views.diary_vote, name='diary_vote'),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .media_form import UserProfile
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    profile_image = forms.ImageField(required=False)  # 프로필 이미지를 업로드할 수 있는 필드 추가

    class Meta:
        model = get_user_model()
        fields = ("username", "password1", "password2" , "email", "first_name", "last_name")

class ModifyForm(UserChangeForm):
    email = forms.EmailField(label="이메일")

    class Meta :
        model = get_user_model()
        fields = ("email", "first_name", "last_name")

common/views/reset_views.py
from django.contrib.auth.views import PasswordResetView,PasswordResetConfirmView
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy

from func.user_manage import check_email

class UserPasswordResetView(PasswordResetView) : 
    template_name = 'common/password_reset.html'
    email_template_name = 'common/email/password_reset_email.html'
    subject_template_name = 'common/email/password_reset_subject.txt'
    success_url = reverse_lazy("common:password_reset_done")

    def form_valid(self, form):
        username = self.request.POST.get('username')
        email = self.request.POST.get('email')
        check = check_email(username, email)
        if check :
            opts = {
                'use_https': self.request.is_secure(),
                'token_generator': self.token_generator,
                'from_email': self.from_email,
                'email_template_name': self.email_template_name,
                'subject_template_name': self.subject_template_name,
                'request': self.request,
                'html_email_template_name': self.html_email_template_name,
                'extra_email_context': self.extra_email_context,
            }
            form.save(**opts)
            return super(PasswordResetView, self).form_valid(form)
        else :
            messages.error(self.request, '이메일과 아이디가 일치하지 않습니다.')
            return self.form_invalid(form)
    
class UserPasswordResetConfirmView(PasswordResetConfirmView) : 
    success_url = reverse_lazy("common:password_reset_complete")
    

common/views/user_views.py
from django.contrib.auth import authenticate, login,logout, update_session_auth_hash
from django.shortcuts import render,redirect
from django.contrib import messages
from common.forms import UserForm,ModifyForm
from django.db.models import Count
from common.media_form import UserProfile, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from diary.forms import CreateDiary, Answer
from django.core.paginator import Paginator  
from django.contrib.auth.forms import PasswordChangeForm
import os
from django.conf import settings


def logout_view(request):
    logout(request)
    return redirect('diary:index')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()  # User 모델 저장
            messages.success(request, '회원가입이 완료되었습니다')

            # 프로필 이미지 업로드
            profile_image = request.FILES.get('profile_image')
            if profile_image:
                user_profile = UserProfile.objects.create(user=user, profile_image=profile_image)

            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

@login_required(login_url='common:login')
def update(request):
    if request.method == 'POST' :
        form = ModifyForm(request.POST, instance=request.user)
        if form.is_valid() :
            form.save()
            messages.success(request, '회원정보가 성공적으로 변경되었습니다.')
            return redirect('common:mypage')
    else :
        form = ModifyForm(instance=request.user)

    return render(request, 'common/update.html', {'form': form})

@login_required(login_url='common:login')
def modify_password(request):
    if request.method == 'POST' :
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid() :
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, '비밀번호가 성공적으로 변경되었습니다.')
            return redirect('common:mypage')
    else :
        form = PasswordChangeForm(request.user)

    return render(request, 'common/modify_password.html', {'form': form})

@login_required(login_url='login')
def delete(request) :
    if request.user.is_authenticated :
        request.user.delete()
        logout(request)
        messages.success(request, '회원탈퇴가 완료되었습니다. 그동안 감사했습니다.')
        return redirect('index')
    


@login_required(login_url='common:login')
def mypage(request):
    current_user_id = request.user.id # 현재 로그인 한사람 

    page = request.GET.get('page','1') # 페이지

    # 현재 로그인된 사용자가 적은 일기중 public 된것만 가져오기
    diary_list1 = CreateDiary.objects.filter(author_id=current_user_id).order_by('-create_date')

    # 현재 로그인된 사용자가 작성한 댓글이 있는 CreateDiary 가져오기
    user_comment_diary = Answer.objects.filter(author_id=current_user_id).values('question_id').annotate(question_count=Count('question_id')).order_by('-question_count')
    comment_diary = [CreateDiary.objects.get(pk=question['question_id']) for question in user_comment_diary]

    # 현재 로그인한 사용자가 추천한(public) 일기 중 voter(추천)를 누른 CreateDiary 가져오기
    user_recommend_diary = CreateDiary.objects.filter(disclose='public', voter__id=current_user_id)

    # 현재 로그인한 사용자가 작성한(public) 글 중 voter(추천)를 받은 CreateDiary 가져오기
    recommend_diary = CreateDiary.objects.filter(author_id=current_user_id, voter__isnull=False)

    user_profile = UserProfile.objects.filter(user=request.user).first()  # 프로필 조회
    if user_profile:
        image_path = user_profile.profile_image.url if user_profile.profile_image else None
    else:
        image_path = None

    # Paginator 적용
    paginator_diary_list1 = Paginator(diary_list1, 5)
    paginator_comment_diary = Paginator(comment_diary, 5)
    paginator_user_recommend_diary = Paginator(user_recommend_diary, 5)
    paginator_recommend_diary = Paginator(recommend_diary, 5)

    page_diary_list1 = paginator_diary_list1.get_page(page)
    page_comment_diary = paginator_comment_diary.get_page(page)
    page_user_recommend_diary = paginator_user_recommend_diary.get_page(page)
    page_recommend_diary = paginator_recommend_diary.get_page(page)

    context = {
        'user_profile': user_profile,
        'image_path': image_path,
        'page_diary_list1': page_diary_list1,
        'page_comment_diary': page_comment_diary,
        'page_user_recommend_diary': page_user_recommend_diary,
        'page_recommend_diary': page_recommend_diary,
    }
    return render(request, 'common/my_page.html', context)

def profile(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        image_path = user_profile.profile_image.url if user_profile.profile_image else None
    except UserProfile.DoesNotExist:
        # 사용자 프로필이 없는 경우, 새로운 프로필을 생성합니다.
        user_profile = UserProfile.objects.create(user=request.user)
        image_path = None

    context = {'user_profile': user_profile, 'image_path': image_path}
    return render(request, 'common/profile.html', context)

def profile_update(request):
    if request.method == "POST":
        # 현재 사용자의 프로필을 가져옴 / 만약 프로필이 없는 경우 빈 프로필을 생성
        user_profile,created = UserProfile.objects.get_or_create(user=request.user)

        # 기존 파일이 존재하는지 확인하고 삭제
        previous_image_path = user_profile.profile_image.path if user_profile.profile_image else None
        if previous_image_path:
            if os.path.exists(previous_image_path):
                os.remove(previous_image_path)

        form = ProfileUpdateForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():

            form.save() # 폼 데이터 저장
            return redirect('common:mypage') # 프로필 업데이트 후에는 마이 페이지로 이동
    else:
        # GET 요청일 때는 현재 사용자의 프로필을 가져와 폼에 넘겨줌
        user_profile,created = UserProfile.objects.get_or_create(user=request.user)
        form = ProfileUpdateForm(instance=user_profile)
    
    return render(request, 'common/profile_update.html', {'form': form})

templates/common/login.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/common/login.css' %}">
<main>
    <div class="container">
        <div class="container">
            <div class="login_box">
                <div class="login_title">로그인</div>
                <div class="login_form">
                    <form method="post" action="{% url 'common:login' %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
                        {% include "form_errors.html" %}
                        <div class="mb-3">
                            <label for="username">사용자ID</label>
                            <input placeholder="Id" type="text" class="form-control" name="username" id="username"
                                   value="{{ form.username.value|default_if_none:'' }}">
                        </div>
                        <div class="mb-3">
                            <label for="password">비밀번호</label>
                            <input placeholder="Password" type="password" class="form-control" name="password" id="password"
                                   value="{{ form.password.value|default_if_none:'' }}">
                        </div>
                        <button type="submit" class="btn btn-primary">로그인</button>
                        <div class="ext_login">
                            <span class="login_css_text">
                                <a href="../password_reset">비밀번호 찾기 </a>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

templates/common/modify_password.html
{% extends 'base.html' %}

{% load custom_date %}
{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/common/login.css' %}">

<main>
    <div class="container">
        <div class="login_box">
            <div class="login_title">비밀번호 변경하기</div>
            <div class="login_form">
                <form method="post" action="">
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="mb-3">
                        <label for="old_password">기존 비밀번호</label>
                        <input placeholder="Old Password" type="password" name="old_password" id="old_password">
                    </div>
                    <div class="mb-3">
                        <label for="new_password1">새 비밀번호</label>
                        <input placeholder="New Password" type="password" name="new_password1" id="new_password1">
                    </div>
                    <div class="mb-3">
                        <label for="new_password2">비밀번호 확인</label>
                        <input placeholder="New Password Check" type="password" name="new_password2" id="new_password2">
                    </div>
                    <button type="submit" class="submit">변경하기</button>
                </form>
            </div>
        </div>
    </div>
</main>


{% endblock %}

templates/common/password_reset.html
{% extends 'base.html' %}

{% load custom_date %}
{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/common/mypage.css' %}">
<link rel="stylesheet" href="{% static 'css/common/login.css' %}">

<main>
    <div class="container">
        <div class="login_box">
            <div class="login_title">비밀번호 찾기</div>
            <div class="login_form">
                <form method="post">
                    {% if messages %}
                        <div class="alert alert-danger" role="alert">
                    {% for message in messages %}
                            <strong>{{ message.tags }}</strong>
                            <ul><li>{{ message.message }}</li></ul>
                    {% endfor %}
                        </div>
                    {% endif %}
    
                    {% csrf_token %}
                    <label for="username">아이디</label>
                    <input placeholder="Id"  type="text" name="username" id="username">
                    <label for="email">이메일</label>
                    <input placeholder="Email"  type="email" name="email" id="email">
                    <input type="submit" value="비밀번호 찾기" class="submit">
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

templates/common/password_reset_done.html
{% extends 'base.html' %}

{% load custom_date %}
{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/common/mypage.css' %}">

<main>
    <div class="container">
        <h2>이메일이 전송되었습니다.</h2>
    </div>
</main>


{% endblock %}

templates/common/profile.html
{% extends 'base.html' %}

{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/common/mypage.css' %}">
<link rel="stylesheet" href="{% static 'css/common/profile.css' %}">

<main>
    <div class="container">
        <div class="update_profile_box">
            <div class="profile_box">
                {% if image_path %}
                    <span 
                        style="background: url({{ image_path }});background-position: center;background-size: cover;background-repeat: no-repeat;">
                    </span>
                {% else %}
                    <img src="{% static 'img/common/default_image.png' %}" alt="Default Image" style="max-width: 200px; max-height: 200px;">
                {% endif %}
            </div>
            
            <div class="update_box">
                <div id="image-preview-container">
                    <img id="image-preview" src="#" alt="미리보기" style="display: none; max-width: 200px;">
                </div>
                <form method="post" action="{% url 'common:profile_update' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="profile_image" class="input-file-button">업로드</label> 
                    <input type="file" name="profile_image" id="profile_image" style="display: none;"onchange="previewImage(event);">
                    <button type="submit" id="update_btn" class="btn btn-primary" style="display: none;">변경하기</button>
                </form>

            </div>
            
        </div>
    </div>
</main>

{% endblock %}

{% block script %}

<script type='text/javascript'>
    const profileForm = document.getElementById("profileForm");
    if (profileForm) {
        profileForm.addEventListener('submit', function(event) {
            event.preventDefault(); // 폼 제출 기본 동작 방지
            // 프로필 업데이트 후에 마이 페이지로 이동
            window.location.href = "{% url 'common:mypage' %}";
            // 폼을 제출
            this.submit();
        });
    }

    function previewImage(event) {
        var input = event.target;
        var preview = document.getElementById('image-preview');
        var submitbtn = document.getElementById('update_btn');

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                preview.src = e.target.result;
                preview.style.display = 'block';
                submitbtn.style.display = 'inline-block';
            }

            reader.readAsDataURL(input.files[0]);
        } else {
            preview.src = '#';
            preview.style.display = 'none';
            submitbtn.style.display = 'none';
        }
    }
</script>
{% endblock %}

templates/common/set_password.html
{% extends 'base.html' %}

{% load custom_date %}
{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/common/mypage.css' %}">

<main>
    <div class="container">
        <div class="my-3">
            {% if validlink %}
            <form method="post" action="">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="mb-3">
                    <label for="new_password1">새 비밀번호</label>
                    <input placeholder="New Password" type="password" name="new_password1" id="new_password1">
                </div>
                <div class="mb-3">
                    <label for="new_password2">비밀번호 확인</label>
                    <input placeholder="New Password Check" type="password" name="new_password2" id="new_password2">
                </div>
                <button type="submit" class="btn btn-primary">설정하기</button>
            </form>
            {% else %}
                <h3>만료된 페이지입니다.</h3>
            {% endif %}
        </div>
    </div>
</main>


{% endblock %}

templates/common/set_password_done.html
{% extends 'base.html' %}

{% load custom_date %}
{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/common/mypage.css' %}">

<main>
    <div class="container">
        <h2>비밀번호가 성공적으로 재설정되었습니다.</h2>
    </div>
</main>


{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/common/login.css' %}">

<main>
    <div class="container">
        <div class="login_box">
            <div class="login_title">회원가입</div>
            <div class="login_form">
                <form method="post" action="{% url 'common:signup' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="mb-3">
                        <label for="username">사용자 ID</label>
                        <input placeholder="Id" type="text" class="form-control" name="username" id="username"
                               value="{{ form.username.value|default_if_none:'' }}">
                    </div>
                    <div class="mb-3">
                        <label for="password1">비밀번호</label>
                        <input placeholder="Password" type="password" class="form-control" name="password1" id="password1"
                               value="{{ form.password1.value|default_if_none:'' }}">
                    </div>
                    <div class="mb-3">
                        <label for="password2">비밀번호 확인</label>
                        <input placeholder="Password Check" type="password" class="form-control" name="password2" id="password2"
                               value="{{ form.password2.value|default_if_none:'' }}">
                    </div>
                    
                    <div class="mb-3">
                        <label for="frist_name">성</label>
                        <input placeholder="Frist Name" type="frist_name" class="form-control" name="frist_name" id="frist_name"
                               value="{{ form.frist_name.value|default_if_none:'' }}">
                    </div>
                    <div class="mb-3">
                        <label for="last_name">이름</label>
                        <input placeholder="Last Name" type="last_name" class="form-control" name="last_name" id="last_name"
                               value="{{ form.last_name.value|default_if_none:'' }}">
                    </div>
                    <div class="mb-3">
                        <label for="email">이메일</label>
                        <input placeholder="Email" type="text" class="form-control" name="email" id="email"
                               value="{{ form.email.value|default_if_none:'' }}">
                    </div>
                    <div class="mb-3">
                        <input placeholder="Profile" type="file" name="profile_image" id="profile_image">
                    </div>
                    <button type="submit" class="btn btn-primary" id="button_submit">생성하기</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/common/update.html
{% extends 'base.html' %}

{% load custom_date %}
{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link rel="stylesheet" href="{% static 'css/common/login.css' %}">

<main>
    <div class="container">
        <div class="login_box">
            <div class="login_title">회원 정보 수정</div>
            <div class="login_form">
                <form method="post" action="">
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    ID [ {{ user.username }} ]
                    <div class="mb-3">
                        <label for="first_name">성</label>
                        <input placeholder="First Name" type="first_name" class="form-control" name="first_name" id="first_name"
                               value="{{ user.first_name }}">
                    </div>
                    <div class="mb-3">
                        <label for="last_name">이름</label>
                        <input placeholder="Last Name" type="last_name" class="form-control" name="last_name" id="last_name"
                               value="{{ user.last_name }}">
                    </div>
                    <div class="mb-3">
                        <label for="email">이메일</label>
                        <input placeholder="Email" type="text" class="form-control" name="email" id="email"
                               value="{{ user.email }}">
                    </div>
                    <button type="submit" class="submit">수정하기</button>
                    <div class="ext_login">
                        <span class="login_css_text">
                            <a href="{% url 'common:modify_password' %}">비밀번호 수정</a>  
                            <a href="{% url 'common:delete' %}" id="delete">회원탈퇴</a>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>


{% endblock %}
{% block script %}
<script type='text/javascript'>
    const deleteForm = document.getElementById("delete");
    if (deleteForm) {
        deleteForm.addEventListener('click', function(event) {
            event.preventDefault(); // 폼 제출 기본 동작 방지
            if (confirm("정말로 탈퇴 하시겠습니까?")) {l
                window.location.href = this.href;
            };
        });
    }

</script>
{% endblock %}