common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import reset_views,user_views

app_name = 'common'

urlpatterns = [
    path('my_page/', user_views.mypage, name='mypage'),
    path('profile/', user_views.profile, name='profile'),
    path('profile_update/', user_views.profile_update, name='profile_update'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('signup/', user_views.signup, name='signup'),
    path('update/', user_views.update, name='update'),
    path('modify_password/', user_views.modify_password, name='modify_password'),
    path('delete/', user_views.delete, name='delete'),

    path('password_reset', reset_views.UserPasswordResetView.as_view()),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(template_name='common/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', reset_views.UserPasswordResetConfirmView.as_view(template_name='common/set_password.html'), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='common/set_password_done.html'), name="password_reset_complete"),
]

diary/urls.py
from django.urls import path
from django.contrib import admin
# 이미지를 업로드하자
from django.conf.urls.static import static
from django.conf import settings

from .views import base_views, diary_views, answer_views

app_name = 'diary'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('diary/', base_views.diary_list, name='diary_list'),
    path('diary_ajax/', base_views.diary_ajax, name='diary_ajax'),
    path('diary/every', base_views.diary_every, name='diary_every'),
    path('diary/<int:diary_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:diary_id>/', answer_views.answer_create, name='answer_create'),
    path('diary/create/', diary_views.diary_create, name='diary_create'),
    path('diary/modify/<int:diary_id>/', diary_views.diary_modify, name='diary_modify'),
    # path('diary/delete_photo/<int:diary_id>/', diary_views.delete_photo, name='delete_photo'),
    path('diary/delete/<int:diary_id>/', diary_views.diary_delete, name='diary_delete'),
    path('answer/modify/<int:answer_id>/<int:diary_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/<int:diary_id>/', answer_views.answer_delete, name='answer_delete'),
    path('diary/vote/<int:diary_id>/', base_views.diary_vote, name='diary_vote'),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from ..models import CreateDiary, Answer
from django.utils import timezone
from ..forms import DiaryForm, AnswerForm
from django.core.paginator import Paginator  
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Count
from django.db.models import Q 
from django import template
from ..templatetags.custom_date import relative_time
from common.views import mypage
from common.media_form import UserProfile
from datetime import date
from django.http import JsonResponse
from django.forms.models import model_to_dict
from datetime import timedelta

register = template.Library()
register.filter('relative_time', relative_time)

def index(request):
    return render(request, 'index.html')

def diary_list(request):
    year = request.GET.get('year')
    month = request.GET.get('month')
    day = request.GET.get('day')
    
    if year and month and day:
        try:
            day = int(day)
            # day 값에서 1을 빼기
            day += 1
            create_date = date(int(year), int(month), day)
        except ValueError:
            create_date = None
    else :
        create_date = None

    if create_date:
        diary_list = CreateDiary.objects.filter(
            author_id=request.user.id,
            create_date=create_date
        ).order_by('-create_date')
    else:
        diary_list = CreateDiary.objects.filter(author_id=request.user.id).order_by('-create_date')

    paginator = Paginator(diary_list, 10) # 페이지당 10개씩 보여주기
    page = request.GET.get('page','1') # 페이지
    page_obj = paginator.get_page(page)

    context = {'diary_list':page_obj}

    return render(request, 'diary/diary_list.html', context)

def diary_ajax(request):
    year = request.GET.get('year')
    month = request.GET.get('month')
    day = request.GET.get('day')
    
    if year and month and day:
        try:
            create_date = date(int(year), int(month), int(day) )
        except ValueError:
            create_date = None
    else :
        create_date = None

    if create_date:
        diary_list = CreateDiary.objects.filter(
            author_id=request.user.id,
            create_date=create_date
        ).order_by('-create_date')
    else:
        diary_list = CreateDiary.objects.filter(author_id=request.user.id).order_by('-create_date')

    data = []
    for diary in diary_list:
        print('diary : ', diary)
        diary_dict = model_to_dict(diary)
        # 필요한 필드만 선택하여 딕셔너리에 추가
        diary_data = {
            'create_date': diary_dict['create_date'],
            'title': diary_dict['title'],
            'disclose': diary_dict['disclose'],
            # 필요한 필드 추가
        }
        data.append(diary_data)
    return JsonResponse(data, safe=False)


def detail(request, diary_id):
    diary = CreateDiary.objects.get(diary_id=diary_id)
    create_date = diary.create_date
    previous_day = create_date - timedelta(days=1)

    try:
        user_profile = UserProfile.objects.get(user_id=diary.author_id)
        if user_profile :
            image_path = user_profile.profile_image.url if user_profile.profile_image else None
        else:
            image_path = None
    except UserProfile.DoesNotExist:
        image_path = None

    context = {'diary':diary, 'image_path':image_path, 'previous_day': previous_day}
    return render(request, 'diary/diary_detail.html', context)


@login_required(login_url='common:login')
def diary_vote(request, diary_id):
    diary = get_object_or_404(CreateDiary, pk=diary_id)
    if request.user == diary.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        diary.voter.add(request.user)
    return redirect('diary:detail', diary_id=diary.diary_id)

def diary_every(request):
    page = request.GET.get('page','1') # 페이지
    diary_list2 = CreateDiary.objects.filter(disclose='public').order_by('-create_date')
    
    # Best Diaries comment
    most_common_questions = Answer.objects.values('question_id').annotate(question_count=Count('question_id')).order_by('-question_count')[:3]
    best_diaries = [CreateDiary.objects.get(pk=question['question_id']) for question in most_common_questions]
    
    # Best Diaries recommend
    recommend_questions = CreateDiary.objects.annotate(voter_count=Count('voter')).order_by('-voter_count')[:3]

    # 검색 
    
    content = request.GET.get('content','전체')
    kw = request.GET.get('kw', '')  # 검색어

    if content == '전체':
        diary_list2 = diary_list2
    elif content == '제목/내용':
        diary_list2 = diary_list2.filter(
            Q(title__icontains=kw)  # 제목 검색
        ).distinct()
    elif content == '답변':
        diary_list2 = diary_list2.filter(
            Q(content__icontains=kw)  # 내용 검색
        ).distinct()
    elif content == '일기 글쓴이':
        diary_list2 = diary_list2.filter(
            Q(author__username__icontains=kw)  # 질문 글쓴이 검색
        ).distinct()
    elif content == '답변 글쓴이':
        diary_list2 = diary_list2.filter(
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    else :
        diary_list2 = diary_list2.filter(
            Q(title__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    # kw = request.GET.get('kw', '')  # 검색어
    # if kw:
    #     diary_list2 = diary_list2.filter(
    #         Q(title__icontains=kw) |  # 제목 검색
    #         Q(content__icontains=kw) |  # 내용 검색
    #         Q(answer__content__icontains=kw) |  # 답변 내용 검색
    #         Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
    #         Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
    #     ).distinct()


    paginator = Paginator(diary_list2, 10) # 페이지당 10개씩 보여주기                                                   
    page_obj = paginator.get_page(page)

    context = {
        'diary_list2':page_obj,
        'best_diaries': best_diaries,
        'recommend_questions': recommend_questions,
        'page': page, 'kw': kw
    }

    return render(request, 'diary/diary_every_list.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>하루하루</title>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.1.0.js"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://webfontworld.github.io/SCoreDream/SCoreDream.css" rel="stylesheet">
    <script src="{% static 'js/base.js' %}"></script>
</head>
<body>

<header>
    <div class="container">
        <div class="logo_box">
            <a href="{% url 'diary:index' %}">
                <img src="{% static 'img/common/logo.png' %}" alt="">
            </a>
        </div>
        <ul class="menu_box">
            <li><a href="{% url 'common:mypage' %}">나의 하루</a></li>
            <li><a href="{% url 'diary:diary_every' %}">모두의 하루</a></li>
            <li>
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.first_name }}{{ user.last_name }} (로그아웃)</a>
                {% else %}
                    <a href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li>
                {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                {% endif %}
            </li>
        </ul>
        
        <!-- 햄버거버튼 (모바일 일때만 보이도록) -->
        <div class="ham_box">
            <div class="ham_icon_box ham">
                <span class="ham_line ham_top"></span>
                <span class="ham_line ham_center"></span>
                <span class="ham_line ham_bottom"></span>            
            </div>
            
            <div class="ham_menu_box">
                <ul class="ham_ul">
                    <li class="my_content">
                        <a href="{% url 'common:mypage' %}">
                            <div class="my_name">{{ user.first_name }}{{ user.last_name }} 님</div>
    
                            <!-- <div class="my_name">로그인 해주세요</div> -->
                        </a>
                    </li>
                    <li class="ham_li"><a href="{% url 'common:mypage' %}">나의 하루</a></li>
                    <li class="ham_li"><a href="{% url 'diary:diary_every' %}">모두의 하루</a></li>
                    <li class="ham_li">
                        {% if user.is_authenticated %}
                            <a href="{% url 'common:logout' %}">{{ user.first_name }}{{ user.last_name }} (로그아웃)</a>
                        {% else %}
                            <a href="{% url 'common:login' %}">로그인</a>
                        {% endif %}
                    </li>
                    <li class="ham_li">
                        {% if not user.is_authenticated %}
                            <a href="{% url 'common:signup' %}">회원가입</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

<footer>
    <div class="container">
        <a href="#">하루하루</a>
    </div>
</footer>


<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
</html>

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger" style="display: flex;
                                flex-wrap: wrap;
                                gap: 20px;
                                align-items: center;">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div style="background: #ffecec;
                padding: 10px 20px;
                box-sizing: border-box;
                border-radius: 10px;
                border: 2px solid #fad9d7;
                text-align: center;
                color: #555555;
                font-size: 15px;">
        <strong style="color: red;">{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div style="background: #e3f7fc;
                padding: 10px 20px;
                box-sizing: border-box;
                border-radius: 10px;
                border: 2px solid #b9e7f9;
                text-align: center;
                color: #555555;
                font-size: 15px;">
        <strong style="color: #03a9f4;">{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/index.html
{% extends 'base.html' %}

{% load custom_date %}
{% load diary_filter %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<script src="{% static 'js/calendar/calendar.js' %}"></script>
<script src="{% static 'js/calender/reserve.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/diary/diary_list.css' %}">
<link rel="stylesheet" href="{% static 'css/index.css' %}">

<main>
    <div class="container">
        <div class="calendar">
            <form action="{% url 'diary:diary_list' %}" id="myForm">
                <div class="calendar_header">
                    <div class="ym-wrapper">
                        <span class="year"></span>년
                        <span class="month"></span>월
                    </div>
                    <div class="calendar_nav">
                        <div class="nav-btn go-prev">&lt;</div>
                        <div class="nav-btn go-today"><a href="#" onClick="history.go(0)">오늘</a> </div>
                        <div class="nav-btn go-next">&gt;</div>
                    </div>
                </div>
                <div class="calendar_main">
                    <div class="days">
                        <div class="day">일</div>
                        <div class="day">월</div>
                        <div class="day">화</div>
                        <div class="day">수</div>
                        <div class="day">목</div>
                        <div class="day">금</div>
                        <div class="day">토</div>
                    </div>
                    <div class="dates"></div>
                </div>
            </form>
            
        </div>

    </div>
</main>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        // var diaryListURL = "{% url 'diary:diary_list' %}";
        $('.dates').on('click', '.date',function(){
            $(this).addClass('click_date');
            $('.date').not(this).removeClass('click_date');
            $('.other').removeClass('click_date');

            var year = $('.ym-wrapper .year').text()
            var month = $('.ym-wrapper .month').text()
            var day = $(this).find('.date-itm').text().split('\n')[1].split(' ')[24]

            var diaryListURL = '/diary/?year=' + year + '&month=' + month + '&day=' + (Number(day));

            // GET 요청 보내기
            $.ajax({
                type: "GET",
                url: diaryListURL,
                success: function(response) {
                    window.location.href = diaryListURL;
                },
                error: function(xhr, errmsg, err) {
                    console.log('GET 요청이 실패했습니다.');
                    console.log(xhr, errmsg, err);
                }
            });



        })
        var requests = [];
        var dates = [];
        var date_counts = [];

        var year = $('.ym-wrapper .year').text()
        var month = $('.ym-wrapper .month').text()
        $('.date-itm').each(function() {
            var day = $(this).text().trim();
            // var diaryListURL = '/diary_ajax/?year=' + year + '&month=' + month + '&day=' + day;

            // 각 날짜마다 AJAX 요청을 보냄
            var request = $.ajax({
                type: "GET",
                url: '/diary_ajax/',
                data: {
                    'year': year,
                    'month': month,
                    'day': day
                },
                dataType: 'json'
            });

            requests.push(request);

        });

        $.when.apply($, requests).then(function() {
            let dateCounts = {};
            for (let i = 0; i < arguments.length; i++) {
                let res = arguments[i][0];
                if (res.length >= 1) {
                    for (item of res) {
                        let date = item.create_date.split('T')[0];
                        dateCounts[date] = (dateCounts[date] || 0) + 1;
                    }
                }
            }

            let totalDateCount = 0;
            for (let date in dateCounts) {
                totalDateCount += dateCounts[date];
                dates.push(date);
            }
            date_counts.push(totalDateCount);
            processData(dates, date_counts);
        }, function() {
            console.log('하나 이상의 AJAX 요청이 실패했습니다.');
        });


        $('.nav-btn').on('click',function(){
            processData(dates, date_counts);
        })

    })

</script>
{% endblock %}